name: Update Packages

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "packages.yml"

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'Production' || 'Development' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}

      - name: Deploy Function
        run: |
          gcloud config set functions/region us-central1
          echo "Querying BigQuery for client IDs and names..."
          bq query --format=json --use_legacy_sql=false \
            "SELECT DISTINCT c.client_id, c.client_name \
            FROM \`${{ vars.PROJECT_ID }}.edm_insights_metadata.client_git\` AS cg \
            LEFT JOIN \`${{ vars.PROJECT_ID }}.edm_insights_metadata.client\` AS c USING (client_id) \
            WHERE updated_by_user = False" | awk '/^\[/{p=1}p' > query_results.json
          cat query_results.json
          echo "Sending a Pub/Sub message on packages.yml change..."
          cat query_results.json | jq -c '.[] | {client_id, client_name}' | while read -r line; do
            client_id=$(echo $line | jq -r '.client_id')
            client_name=$(echo $line | jq -r '.client_name')
            echo "Publishing message: Client ID: $client_id, Client Name: $client_name, DBT Template Repo Branch: ${{ github.ref_name }}"
            gcloud pubsub topics publish ${{ vars.UPDATE_PACKAGE_TOPIC }} --message "{\"client_id\": \"$client_id\", \"client_name\": \"$client_name\", \"update_package\": true, \"dbt_template_repo_branch\": \"${{ github.ref_name }}\"}"
          done
